 function CabecalhoZS() {
   let CabecalhoZS = `<!doctype html>\n<html>\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">\n<meta name="HTMLMaker_v1.3.2" content="plusoft-tpl">\n<title>Zona Sul</title>\n<style>\nbody{margin:0; padding:0}\nimg{margin:0; padding:0; }\na[href^=tel]{ color:#666666; text-decoration:none;}\na[href^=date]{ color:#666666; text-decoration:none;}\nhr {margin:0 !important}\ndiv, p, a, li, td {-webkit-text-size-adjust:none;}\n\n</style>\n</head>\n<body>\n<div style="font-size:0px;line-height:1px;mso-line-height-rule:exactly;display:none;max-width:0px;max-height:0px;opacity:0;overflow:hidden;mso-hide:all;">\nINSERIR PREHEADER AQUI\n</div>\n<div style="margin:0; padding:0;" bgcolor="#ffffff">\n\n\n<table width="100%" cellpadding="0" cellspacing="0" border="0" align="center" style="table-layout: fixed" bgcolor="#F4F4F4"><tr><td align="center" valign="top">\n\n<!--[if mso]><table width="680" cellpadding="0" cellspacing="0" border="0" align="center"><tr><td align="center" valign="top"><![endif]-->\n<table width="100%" cellpadding="0" cellspacing="0" border="0" align="center" style="max-width:680px" bgcolor="#ffffff">\n`;
   return CabecalhoZS
  
}


function CabecalhoCOOP(lineColor) {
   let CabecalhoCOOP = `<!doctype html>\n<html>\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">\n<meta name="HTMLMaker_v1.3.2" content="plusoft-tpl">\n<title>HTML</title>\n<style>\nbody{margin:0; padding:0}\nimg{margin:0; padding:0; }\na[href^=tel]{ color:#666666; text-decoration:none;}\na[href^=date]{ color:#666666; text-decoration:none;}\nhr {margin:0 !important}\ndiv, p, a, li, td {-webkit-text-size-adjust:none;}\n\n</style>\n</head>\n<body>\n<div style="margin:0; padding:0;" bgcolor="#EFEFEF">\n<table width="100%" cellpadding="0" cellspacing="0" border="0" align="center" style="table-layout: fixed; border-top: 9px solid ${lineColor}; border-bottom: 9px solid ${lineColor}" bgcolor="#EFEFEF"><tr><td align="center" valign="top">\n<!--[if mso]><table width="680" cellpadding="0" cellspacing="0" border="0" align="center"><tr><td align="center" valign="top"><![endif]-->\n<table width="100%" cellpadding="0" cellspacing="0" border="0" align="center" style="max-width:680px" bgcolor="#002747">\n`;
   return CabecalhoCOOP
  
}

function CabecalhoFPM() {
   let CabecalhoFPM = `<!doctype html>\n<html xmlns:mso="urn:schemas-microsoft-com:office:office" xmlns:msdt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">\n<meta name="HTMLMaker_v1.3.2" content="plusoft-tpl">\n<title>Farmácias Pague Menos</title>\n<style>\nbody{margin:0; padding:0}\nimg{margin:0; padding:0; }\na[href^=tel]{ color:#666666; text-decoration:none;}\na[href^=date]{ color:#666666; text-decoration:none;}\nhr {margin:0 !important}\ndiv, p, a, li, td {-webkit-text-size-adjust:none;}\n</style>\n\n<!--[if gte mso 9]><xml>\n<mso:CustomDocumentProperties>\n<mso:_dlc_DocId msdt:dt="string">QA7UY62FZWNU-450026745-66730</mso:_dlc_DocId>\n<mso:_dlc_DocIdItemGuid msdt:dt="string">bcb93950-5386-427d-b15c-ea5acc77019f</mso:_dlc_DocIdItemGuid>\n<mso:_dlc_DocIdUrl msdt:dt="string">https://plusoft.sharepoint.com/sites/Fileserver_DTM-Criacao/_layouts/15/DocIdRedir.aspx?ID=QA7UY62FZWNU-450026745-66730, QA7UY62FZWNU-450026745-66730</mso:_dlc_DocIdUrl>\n</mso:CustomDocumentProperties>\n</xml><![endif]-->\n</head>\n<body>\n%%[\nSET @TipoLike = 'https://cloud.email.paguemenos.com.br/avaliacao?tipo=LIKE&qs1='\nSET @TipoDislike = 'https://cloud.email.paguemenos.com.br/avaliacao?tipo=DISLIKE&qs1='\nSET @Subscriber = AttributeValue("subscriberkey")\nSET @EmailAddress = AttributeValue("Emailaddr")\nSET @JobId = AttributeValue("JobId")\nSET @EmailName = AttributeValue("emailname")\nSET @AvaliacaoSubscriber = Base64Encode(@Subscriber)\nSET @AvaliacaoSubscriberConcat = CONCAT(@AvaliacaoSubscriber,'&qs2=')\nSET @AvaliacaoEmailAddress = Base64Encode(@EmailAddress)\nSET @AvaliacaoEmailAddressConcat = CONCAT(@AvaliacaoEmailAddress,'&qs3=')\nSET @AvaliacaoJobid = Base64Encode(@Jobid)\nSET @AvaliacaoJobidConcat = CONCAT(@AvaliacaoJobid,'&qs4=')\nSET @AvaliacaoEmailName = Base64Encode(@EmailName)\nSET @LinkAvaliacaoLike = CONCAT(@TipoLike,@AvaliacaoSubscriberConcat,@AvaliacaoEmailAddressConcat,@AvaliacaoJobidConcat,@AvaliacaoEmailName)\nSET @LinkAvaliacaoDislike = CONCAT(@TipoDislike,@AvaliacaoSubscriberConcat,@AvaliacaoEmailAddressConcat,@AvaliacaoJobidConcat,@AvaliacaoEmailName)\n]%%\n<div style="margin:0; padding:0;" bgcolor="#ffffff">\n<table width="100%" cellpadding="0" cellspacing="0" border="0" align="center" style="table-layout: fixed;" bgcolor="#E5F2F9"><tr><td align="center" valign="top">\n\n<!--[if mso]><table width="680" cellpadding="0" cellspacing="0" border="0" align="center"><tr><td align="center" valign="top"><![endif]-->\n<table width="100%" cellpadding="0" cellspacing="0" border="0" align="center" style="max-width:680px">\n`;
   return CabecalhoFPM
  
}

function CabecalhoEXF() {
   let CabecalhoEXF = `<!doctype html>\n<html xmlns:mso="urn:schemas-microsoft-com:office:office" xmlns:msdt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">\n<meta name="HTMLMaker_v1.3.2" content="plusoft-tpl">\n<title>Extrafarma</title>\n<style>\nbody{margin:0; padding:0}\nimg{margin:0; padding:0; }\na[href^=tel]{ color:#666666; text-decoration:none;}\na[href^=date]{ color:#666666; text-decoration:none;}\nhr {margin:0 !important}\ndiv, p, a, li, td {-webkit-text-size-adjust:none;}\n</style>\n\n<!--[if gte mso 9]><xml>\n<mso:CustomDocumentProperties>\n<mso:_dlc_DocId msdt:dt="string">QA7UY62FZWNU-450026745-66731</mso:_dlc_DocId>\n<mso:_dlc_DocIdItemGuid msdt:dt="string">478974bb-6cee-4f80-a9d6-4825ea3a4ee7</mso:_dlc_DocIdItemGuid>\n<mso:_dlc_DocIdUrl msdt:dt="string">https://plusoft.sharepoint.com/sites/Fileserver_DTM-Criacao/_layouts/15/DocIdRedir.aspx?ID=QA7UY62FZWNU-450026745-66731, QA7UY62FZWNU-450026745-66731</mso:_dlc_DocIdUrl>\n</mso:CustomDocumentProperties>\n</xml><![endif]-->\n</head>\n<body>\n%%[\nSET @TipoLike = 'https://cloud.email.paguemenos.com.br/avaliacao?tipo=LIKE&qs1='\nSET @TipoDislike = 'https://cloud.email.paguemenos.com.br/avaliacao?tipo=DISLIKE&qs1='\nSET @Subscriber = AttributeValue("_subscriberkey")\nSET @EmailAddress = AttributeValue("Emailaddr")\nSET @JobId = AttributeValue("JobId")\nSET @EmailName = AttributeValue("emailname_")\nSET @AvaliacaoSubscriber = Base64Encode(@Subscriber)\nSET @AvaliacaoSubscriberConcat = CONCAT(@AvaliacaoSubscriber,'&qs2=')\nSET @AvaliacaoEmailAddress = Base64Encode(@EmailAddress)\nSET @AvaliacaoEmailAddressConcat = CONCAT(@AvaliacaoEmailAddress,'&qs3=')\nSET @AvaliacaoJobid = Base64Encode(@Jobid)s\nSET @AvaliacaoJobidConcat = CONCAT(@AvaliacaoJobid,'&qs4=')\nSET @AvaliacaoEmailName = Base64Encode(@EmailName)\nSET @LinkAvaliacaoLike = CONCAT(@TipoLike,@AvaliacaoSubscriberConcat,@AvaliacaoEmailAddressConcat,@AvaliacaoJobidConcat,@AvaliacaoEmailName)\nSET @LinkAvaliacaoDislike = CONCAT(@TipoDislike,@AvaliacaoSubscriberConcat,@AvaliacaoEmailAddressConcat,@AvaliacaoJobidConcat,@AvaliacaoEmailName)\n]%%\n<div style="margin:0; padding:0;" bgcolor="#ffffff">\n<table width="100%" cellpadding="0" cellspacing="0" border="0" align="center" style="table-layout: fixed;" bgcolor="#ffffff"><tr><td align="center" valign="top">\n\n<!--[if mso]><table width="680" cellpadding="0" cellspacing="0" border="0" align="center"><tr><td align="center" valign="top"><![endif]-->\n<table width="100%" cellpadding="0" cellspacing="0" border="0" align="center" style="max-width:680px" bgcolor="#662E8D">\n`;
   return CabecalhoEXF
  
}


module.exports = {CabecalhoCOOP,CabecalhoZS,CabecalhoFPM,CabecalhoEXF}

